var workspace = require('../../../utils/workspace')
var TYPE_OPTIONS = [{id:'referee_absent',text:'裁判未到场'},{id:'data_sync',text:'数据同步中断'},{id:'match_interrupted',text:'比赛暂停/中断'},{id:'venue_equipment',text:'场地或设备问题'},{id:'other',text:'其他'}]
Page({
  data:{loading:true,errorText:'',denied:false,submitting:false,matchId:'',workspaceId:'',match:{},types:[],activeType:'data_sync',description:'',contactName:'',contactPhone:'',evidence:[],evidenceCountText:'0/3',reports:[],hasReports:false,visualQa:false},
onLoad:function(options){if(workspace.isVisualQaEnabled(options)){this.loadVisualFixture();return}var context=workspace.readContext()||{};this.setData({matchId:(options&&options.matchId)||'',workspaceId:(context.currentWorkspace||{}).id||'',types:this.prepareTypes('data_sync')});this.loadData()},
  onPullDownRefresh:function(){var that=this;this.loadData().finally(function(){wx.stopPullDownRefresh()})},
  prepareTypes:function(active){return TYPE_OPTIONS.map(function(item){return{id:item.id,text:item.text,itemClass:item.id===active?'active':''}})},
  loadData:function(){var that=this;var context=workspace.readContext()||{};if(!this.data.matchId){this.setData({loading:false,errorText:'缺少比赛参数'});return Promise.resolve()}if(!workspace.hasPermission('event.manage',context)){this.setData({loading:false,denied:true});return Promise.resolve()}this.setData({loading:true,errorText:''});var db=wx.cloud.database();return Promise.all([new Promise(function(resolve,reject){db.collection('matches').doc(that.data.matchId).get({success:resolve,fail:reject})}),wx.cloud.callFunction({name:'getMiniWorkspace',data:{action:'listMatchExceptions',workspaceId:that.data.workspaceId,matchId:that.data.matchId}})]).then(function(results){var raw=results[0].data||{};var list=(results[1].result||{}).reports||[];that.setData({loading:false,match:{divisionText:raw.divisionName||raw.division||'当前组别',statusText:raw.status==='ongoing'?'进行中':'比赛状态待同步',homeName:raw.homeTeamName||'主队',awayName:raw.awayTeamName||'客队',homeScore:String(raw.homeScore||0),awayScore:String(raw.awayScore||0),refereePhone:raw.refereePhone||''},reports:list,hasReports:list.length>0})}).catch(function(error){that.setData({loading:false,errorText:error.message||'异常数据加载失败'})})},
  onTypeTap:function(e){var id=e.currentTarget.dataset.id||'other';this.setData({activeType:id,types:this.prepareTypes(id)})},onDescriptionInput:function(e){this.setData({description:e.detail.value||''})},onContactNameInput:function(e){this.setData({contactName:e.detail.value||''})},onContactPhoneInput:function(e){this.setData({contactPhone:e.detail.value||''})},
  onChooseEvidence:function(){if(this.data.visualQa){wx.showToast({title:'视觉验收状态不上传证据',icon:'none'});return}var that=this;if(this.data.evidence.length>=3)return;wx.chooseMedia({count:3-this.data.evidence.length,mediaType:['image','video'],sourceType:['album','camera'],success:function(res){var files=res.tempFiles||[];var uploads=files.map(function(file,index){var suffix=(file.tempFilePath.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'');return wx.cloud.uploadFile({cloudPath:'match-exceptions/'+that.data.matchId+'/'+Date.now()+'-'+index+'.'+suffix,filePath:file.tempFilePath})});Promise.all(uploads).then(function(items){var evidence=that.data.evidence.concat(items.map(function(item){return item.fileID}));that.setData({evidence:evidence,evidenceCountText:String(evidence.length)+'/3'})}).catch(function(){wx.showToast({title:'证据上传失败，请重试',icon:'none'})})}})},
  onCallReferee:function(){var phone=this.data.match.refereePhone;if(phone){wx.makePhoneCall({phoneNumber:phone});return}wx.showModal({title:'暂无裁判电话',content:'请通过赛事通讯录联系本场裁判。',showCancel:false})},
  onSubmit:function(){if(this.data.visualQa){wx.showToast({title:'视觉验收状态不提交异常',icon:'none'});return}var that=this;if(this.data.submitting)return;this.setData({submitting:true});wx.cloud.callFunction({name:'getMiniWorkspace',data:{action:'reportMatchException',workspaceId:this.data.workspaceId,matchId:this.data.matchId,type:this.data.activeType,description:this.data.description,contactName:this.data.contactName,contactPhone:this.data.contactPhone,evidenceFileIds:this.data.evidence}}).then(function(res){var result=res.result||{};if(!result.success)throw new Error(result.message||result.error||'提交失败');wx.showToast({title:result.message||'异常已提交',icon:'success'});that.setData({description:'',contactName:'',contactPhone:'',evidence:[],evidenceCountText:'0/3'});that.loadData()}).catch(function(error){wx.showToast({title:error.message||'提交失败',icon:'none'})}).finally(function(){that.setData({submitting:false})})},
  onBackTap:function(){wx.navigateBack()},
  loadVisualFixture:function(){this.setData({loading:false,visualQa:true,matchId:'visual-match',workspaceId:'visual-workspace',types:this.prepareTypes('data_sync'),match:{divisionText:'U12组 · 小组赛第3轮',statusText:'进行中 68′',homeName:'赛小蜂 U12',awayName:'洛阳龙门 U12',homeScore:'2',awayScore:'1',refereePhone:''},contactName:'许老师',contactPhone:'138****1663',reports:[{id:'r1',createdAtText:'08-02 16:38',reporterName:'许老师',description:'现场网络短暂中断，裁判端已恢复同步。',status:'处理中'}],hasReports:true})}
})
