// pages/player/detail.js - 球员创建/编辑
const pinyin = require('../../utils/pinyin.js')

Page({

  data: {
    teamId: '',
    playerId: null,
    isEdit: false,
    role: '',
    // 表单字段
    name: '',
    jerseyName: '',
    jerseyNumber: '',
    position: '',
    isCaptain: false,
    age: '',
    birthDate: '',
    idCard: '',
    phone: '',
    remark: '',
    photo: '',
    nationality: '中国',
    height: '',
    weight: '',
    province: '',
    city: '',
    district: '',
    // 位置选项
    positions: ['守门员', '后卫', '前卫', '前锋'],
    // 国籍选项
    nationalities: [
      '中国', '日本', '韩国', '巴西', '英格兰', '法国', '德国', '意大利',
      '阿根廷', '葡萄牙', '西班牙', '荷兰', '比利时', '克罗地亚'
    ]
  },

  onLoad(options) {
    this.setData({ 
      teamId: options.teamId,
      role: getApp().globalData.userRole || 'coach'
    })
    if (options.playerId) {
      this.setData({ playerId: options.playerId, isEdit: true })
      this.loadPlayer(options.playerId)
    }
  },

  // 加载球员信息
  async loadPlayer(playerId) {
    try {
      const db = wx.cloud.database()
      const res = await db.collection('players').doc(playerId).get()
      this.setData({
        name: res.data.name || '',
        jerseyName: res.data.jerseyName || '',
        jerseyNumber: String(res.data.jerseyNumber || ''),
        position: res.data.position || '',
        isCaptain: res.data.isCaptain || false,
        age: res.data.age || '',
        birthDate: res.data.birthDate || '',
        idCard: res.data.idCard || '',
        phone: res.data.phone || '',
        remark: res.data.remark || '',
        photo: res.data.photo || '',
        nationality: res.data.nationality || '中国',
        height: res.data.height || '',
        weight: res.data.weight || '',
        province: res.data.province || '',
        city: res.data.city || '',
        district: res.data.district || ''
      })
    } catch (err) {
      console.error('加载球员失败:', err)
      wx.showToast({ title: '加载失败', icon: 'none' })
    }
  },
  onNameInput(e) {
    const name = e.detail.value
    let jerseyName = this.data.jerseyName
    if (name.length >= 2 && (!jerseyName || this.data._autoGenerated)) {
      jerseyName = pinyin.generateJerseyName(name)
      this.setData({ _autoGenerated: true })
    }
    this.setData({ name, jerseyName })
  },

  onJerseyNameInput(e) {
    this.setData({ jerseyName: e.detail.value, _autoGenerated: false })
  },

  // 身份证号 → 自动提取年龄和出生日期
  onIdCardInput(e) {
    const idCard = e.detail.value
    const parsed = pinyin.parseIdCard(idCard)
    if (parsed) {
      this.setData({ idCard, birthDate: parsed.birthDate, age: String(parsed.age) })
    } else {
      this.setData({ idCard, birthDate: '', age: '' })
    }
  },

  // 上传球员照片（自动压缩）
  choosePhoto() {
    wx.chooseMedia({
      count: 1,
      mediaType: ['image'],
      success: (res) => {
        const tempPath = res.tempFiles[0].tempFilePath
        this.uploadPhoto(tempPath)
      }
    })
  },

  async uploadPhoto(filePath) {
    wx.showLoading({ title: '上传中...' })
    try {
      // 先压缩图片
      const compressRes = await new Promise((resolve, reject) => {
        wx.compressImage({
          src: filePath,
          quality: 80,
          success: resolve,
          fail: () => resolve({ tempFilePath: filePath })
        })
      })

      const compressedPath = compressRes.tempFilePath || filePath
      const ext = (compressedPath.split('.').pop() || 'jpg').toLowerCase()
      const cloudPath = `player-photos/${Date.now()}-${Math.random().toString(36).substr(2, 8)}.${ext}`
      const res = await wx.cloud.uploadFile({ cloudPath, filePath: compressedPath })

      this.setData({ photo: res.fileID })
      wx.showToast({ title: '上传成功', icon: 'success' })
    } catch (err) {
      console.error('上传失败:', err)
      wx.showToast({ title: '上传失败', icon: 'none' })
    }
    wx.hideLoading()
  },

  onBirthDateChange(e) { this.setData({ birthDate: e.detail.value }) },
  onAgeInput(e) { this.setData({ age: e.detail.value }) },
  onJerseyInput(e) { this.setData({ jerseyNumber: e.detail.value }) },
  onPhoneInput(e) { this.setData({ phone: e.detail.value }) },
  onRemarkInput(e) { this.setData({ remark: e.detail.value }) },
  selectPosition(e) { this.setData({ position: e.currentTarget.dataset.pos }) },
  toggleCaptain() { this.setData({ isCaptain: !this.data.isCaptain }) },
  onNationalityChange(e) {
    this.setData({ nationality: this.data.nationalities[e.detail.value] || '中国' })
  },
  onHeightInput(e) { this.setData({ height: e.detail.value }) },
  onWeightInput(e) { this.setData({ weight: e.detail.value }) },
  onProvinceInput(e) { this.setData({ province: e.detail.value }) },
  onCityInput(e) { this.setData({ city: e.detail.value }) },
  onDistrictInput(e) { this.setData({ district: e.detail.value }) },

  // 保存球员
  async savePlayer() {
    const { name, idCard } = this.data
    if (!name.trim()) {
      wx.showToast({ title: '请输入球员姓名', icon: 'none' })
      return
    }
    if (idCard && idCard.length !== 18) {
      wx.showToast({ title: '身份证号格式不正确', icon: 'none' })
      return
    }

    wx.showLoading({ title: '保存中...' })

    try {
      const db = wx.cloud.database()
      const playerData = {
        name: this.data.name.trim(),
        jerseyName: this.data.jerseyName.trim(),
        jerseyNumber: parseInt(this.data.jerseyNumber) || 0,
        position: this.data.position,
        isCaptain: this.data.isCaptain,
        age: this.data.age ? parseInt(this.data.age) : 0,
        birthDate: this.data.birthDate,
        idCard: this.data.idCard,
        phone: this.data.phone,
        remark: this.data.remark,
        photo: this.data.photo,
        teamId: this.data.teamId,
        nationality: this.data.nationality || '中国',
        height: this.data.height,
        weight: this.data.weight,
        province: this.data.province,
        city: this.data.city,
        district: this.data.district,
        nativePlace: [this.data.province, this.data.city, this.data.district].filter(Boolean).join(''),
        updateTime: db.serverDate()
      }

      if (this.data.isEdit) {
        await db.collection('players').doc(this.data.playerId).update({ data: playerData })
      } else {
        playerData.createTime = db.serverDate()
        playerData.isCreatedByCoach = true
        playerData.isBound = false
        await db.collection('players').add({ data: playerData })
        try {
          const res = await db.collection('teams').doc(this.data.teamId).get()
          await db.collection('teams').doc(this.data.teamId).update({
            data: { playerCount: (res.data.playerCount || 0) + 1 }
          })
        } catch (err) {}
      }

      wx.showToast({ title: '保存成功', icon: 'success' })
      setTimeout(() => wx.navigateBack(), 1500)
    } catch (err) {
      console.error('保存失败:', err)
      wx.showToast({ title: '保存失败', icon: 'none' })
    }
    wx.hideLoading()
  }
})