var cards=require('../../utils/player-card')
Page({
 data:{playerId:'',teamId:'',cardUrl:'',ready:false,portraitUrl:'',hasPortrait:false,canSupplement:false,playerName:'',stateText:'正在加载…'},
 onLoad:function(options){var self=this;this.setData({playerId:String(options.playerId||''),teamId:String(options.teamId||'')});if(this.data.playerId){this.load();return}if(options.identityCardId){wx.cloud.database().collection('identity_cards').doc(options.identityCardId).get().then(function(r){var p=r.data||{};if(!p.playerId){self.setData({stateText:'该旧卡未关联球员'});return}self.setData({playerId:String(p.playerId),teamId:String(p.teamId||'')});self.load()}).catch(function(){self.setData({stateText:'无权读取此卡片'})})}else this.setData({stateText:'缺少球员信息'})},
 onShow:function(){var self=this;this.load();clearInterval(this._timer);this._timer=setInterval(function(){self.load()},60000)},onHide:function(){clearInterval(this._timer)},onUnload:function(){clearInterval(this._timer)},
 load:function(){if(!this.data.playerId||this._busy)return;this._busy=true;var self=this;cards.read(this.data.playerId,this.data.teamId).then(function(c){var photo=c.status==='forbidden'?'':(c.portraitUrl||'');self.setData({ready:c.status==='ready',cardUrl:c.cardUrl||'',portraitUrl:photo,hasPortrait:!!photo,canSupplement:c.status!=='forbidden'&&c.portraitStatus==='missing',playerName:c.playerName||'',stateText:photo?(c.status==='pending'?'成卡更新中':''):c.status==='forbidden'?'无权查看':c.portraitStatus==='failed'?'图片加载异常，请重试':'资料待补充',templateId:c.templateId||'',publishedVersion:c.publishedVersion||0})}).catch(function(e){self.setData({ready:false,cardUrl:'',stateText:e.message||'球员卡读取失败'})}).finally(function(){self._busy=false})},
 saveCard:function(){if(!this.data.ready)return;wx.downloadFile({url:this.data.cardUrl,success:function(r){if(r.statusCode!==200)return wx.showToast({title:'下载失败，请重试',icon:'none'});wx.saveImageToPhotosAlbum({filePath:r.tempFilePath,success:function(){wx.showToast({title:'已保存'})},fail:function(){wx.showToast({title:'保存失败，请检查相册权限',icon:'none'})}})},fail:function(){wx.showToast({title:'下载失败，请重试',icon:'none'})}})},
 preview:function(){var url=this.data.ready?this.data.cardUrl:this.data.portraitUrl;if(url)wx.previewImage({urls:[url]})},supplement:function(){wx.navigateTo({url:'/pages/team/player-detail/player-detail?playerId='+encodeURIComponent(this.data.playerId)+'&teamId='+encodeURIComponent(this.data.teamId)})},portraitFailed:function(){this.setData({hasPortrait:false,stateText:'图片加载异常，请重试'})},imageFailed:function(){this.setData({ready:false,cardUrl:'',stateText:this.data.hasPortrait?'':'图片加载异常，请重试'})}
})
