const https=require('https'),Jimp=require('jimp')
let token='',expires=0
function post(path,body){return new Promise((resolve,reject)=>{const data=new URLSearchParams(body).toString();const req=https.request({hostname:'aip.baidubce.com',path,method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Content-Length':Buffer.byteLength(data)}},res=>{let size=0,parts=[];res.on('data',b=>{size+=b.length;if(size>6*1024*1024)req.destroy(Error('OCR_RESPONSE_TOO_LARGE'));else parts.push(b)});res.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(parts).toString('utf8')))}catch(_){reject(Error('OCR_RESPONSE_INVALID'))}})});req.setTimeout(8000,()=>req.destroy(Error('OCR_TIMEOUT')));req.on('error',reject);req.end(data)})}
function date(value){const text=String(value||'').trim(),digits=text.replace(/[^0-9]/g,'');if(digits.length===8){const iso=digits.slice(0,4)+'-'+digits.slice(4,6)+'-'+digits.slice(6);const d=new Date(iso+'T00:00:00Z');if(Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===iso)return iso}return''}
function fields(result,type){const w=result.words_result||{},word=(...keys)=>{for(const k of keys)if(w[k]&&w[k].words)return String(w[k].words).trim();return''};const number=word(type==='resident_id'?'公民身份号码':'护照号码');return{name:word('姓名'),birthDate:date(word('出生','生日','出生日期')),gender:word('性别'),numberMasked:number?number.slice(0,2)+'********'+number.slice(-4):'',expiry:word('失效日期','有效期至'),issuingAuthority:word('签发机关','签发机关名称'),type}}
async function recognize(buffer,type,side,db){
  if(!process.env.BAIDU_OCR_API_KEY||!process.env.BAIDU_OCR_SECRET_KEY)throw Object.assign(Error('百度证件识别尚未配置'),{code:'OCR_NOT_CONFIGURED'})
  const slot=await db.runTransaction(async tx=>{const ref=tx.collection('system_service_limits').doc('baidu-document-ocr'),r=await ref.get(),row=Array.isArray(r.data)?r.data[0]:r.data,now=Date.now(),at=Math.max(now,Number(row&&row.nextAt||0));if(at-now>3000)return null;await ref.set({data:{nextAt:at+650,updateTime:db.serverDate()}});return at})
  if(slot===null)throw Object.assign(Error('识别服务繁忙，请稍后点击重试'),{code:'OCR_BUSY'})
  if(slot>Date.now())await new Promise(r=>setTimeout(r,slot-Date.now()))
  if(!token||expires<Date.now()){const auth=await post('/oauth/2.0/token',{grant_type:'client_credentials',client_id:process.env.BAIDU_OCR_API_KEY,client_secret:process.env.BAIDU_OCR_SECRET_KEY});if(!auth.access_token)throw Object.assign(Error('证件识别应用授权失效，请联系管理员'),{code:'OCR_AUTH_FAILED'});token=auth.access_token;expires=Date.now()+(Number(auth.expires_in||300)-120)*1000}
  const params={image:buffer.toString('base64')};if(type==='resident_id')Object.assign(params,{id_card_side:side,detect_direction:'true',detect_card:'true',detect_photo:side==='front'?'true':'false',detect_quality:'true',detect_risk:'true'})
  const response=await post('/rest/2.0/ocr/v1/'+(type==='resident_id'?'idcard':'passport')+'?access_token='+encodeURIComponent(token),params)
  if(response.error_code){const n=Number(response.error_code);const message=n===6?'应用尚未授权该证件识别接口':([17,19].includes(n)?'识别额度暂不可用，请联系管理员核对免费资源':(n===18?'识别请求繁忙，请稍后重试':'证件未能识别，请拍摄清晰完整的资料页'));throw Object.assign(Error(message),{code:'BAIDU_OCR_'+n})}
  if(type==='resident_id'&&response.image_status&&response.image_status!=='normal')throw Object.assign(Error(response.image_status==='reversed_side'?'证件面选择不正确，请选择对应的人像面或国徽面':'证件不完整或未能识别，请重新拍摄'),{code:'OCR_IMAGE_INVALID'})
  const recognized=fields(response,type);if((type==='passport'||side==='front')&&(!recognized.name||!recognized.birthDate))throw Object.assign(Error('姓名或出生日期未识别完整，请重新拍摄清晰资料页'),{code:'OCR_FIELDS_INCOMPLETE'})
  let image=await Jimp.read(response.card_image?Buffer.from(String(response.card_image).replace(/^data:image\/[^;]+;base64,/,''),'base64'):buffer)
  const direction=Number(response.direction);if(!response.card_image&&[1,2,3].includes(direction))image.rotate(-90*direction,false)
  if(Math.max(image.bitmap.width,image.bitmap.height)>1600)image.scaleToFit(1600,1600)
  const output=await image.quality(88).getBufferAsync(Jimp.MIME_JPEG)
  let referencePhoto='';if(type==='resident_id'&&side==='front'&&typeof response.photo==='string'&&response.photo.length<2*1024*1024){try{const photo=await Jimp.read(Buffer.from(response.photo.replace(/^data:image\/[^;]+;base64,/,''),'base64'));if(Math.max(photo.bitmap.width,photo.bitmap.height)>512)photo.scaleToFit(512,512);referencePhoto='data:image/jpeg;base64,'+(await photo.quality(92).getBufferAsync(Jimp.MIME_JPEG)).toString('base64')}catch(_){}}
  return{success:true,base64Data:'data:image/jpeg;base64,'+output.toString('base64'),referencePhoto,recognized,cropDetected:!!response.card_image,rotation:[0,1,2,3].includes(direction)?-90*direction:0,needsOrientationConfirmation:!response.card_image,message:type==='resident_id'?'百度身份证识别完成，请核对信息及照片方向':'百度护照识别完成，请核对信息及照片方向',width:image.bitmap.width,height:image.bitmap.height,provider:'baidu-ocr',riskType:String(response.risk_type||''),quality:response.card_quality||null}
}
module.exports={recognize,fields,date}
