const Jimp=require('jimp')
function dimensions(buffer){
  if(buffer.length>=24&&buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)}
  if(buffer[0]===255&&buffer[1]===216){let i=2;while(i+8<buffer.length){if(buffer[i]!==255){i++;continue}let marker=buffer[i+1];if(marker===216||marker===217){i+=2;continue}let length=buffer.readUInt16BE(i+2);if(length<2||i+2+length>buffer.length)break;if([192,193,194].includes(marker))return{height:buffer.readUInt16BE(i+5),width:buffer.readUInt16BE(i+7)};i+=2+length}}
  throw Error('IMAGE_FORMAT')
}
function hull(points){points.sort((a,b)=>a.x-b.x||a.y-b.y);const cross=(o,a,b)=>(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x),lower=[],upper=[];for(const p of points){while(lower.length>=2&&cross(lower.at(-2),lower.at(-1),p)<=0)lower.pop();lower.push(p)}for(let i=points.length-1;i>=0;i--){const p=points[i];while(upper.length>=2&&cross(upper.at(-2),upper.at(-1),p)<=0)upper.pop();upper.push(p)}return lower.slice(0,-1).concat(upper.slice(0,-1))}
function rectangle(points){const polygon=hull(points);if(polygon.length<4)return null;let best=null;for(let i=0;i<polygon.length;i++){let theta=Math.atan2(polygon[(i+1)%polygon.length].y-polygon[i].y,polygon[(i+1)%polygon.length].x-polygon[i].x),c=Math.cos(theta),s=Math.sin(theta),minU=Infinity,maxU=-Infinity,minV=Infinity,maxV=-Infinity;for(const p of polygon){const u=p.x*c+p.y*s,v=-p.x*s+p.y*c;minU=Math.min(minU,u);maxU=Math.max(maxU,u);minV=Math.min(minV,v);maxV=Math.max(maxV,v)}const area=(maxU-minU)*(maxV-minV);if(!best||area<best.area)best={theta,minU,maxU,minV,maxV,area}}if(best.maxU-best.minU<best.maxV-best.minV){best.theta+=Math.PI/2;return rectangleAt(polygon,best.theta)}return best}
function rectangleAt(points,theta){const c=Math.cos(theta),s=Math.sin(theta),r={theta,minU:Infinity,maxU:-Infinity,minV:Infinity,maxV:-Infinity};for(const p of points){let u=p.x*c+p.y*s,v=-p.x*s+p.y*c;r.minU=Math.min(r.minU,u);r.maxU=Math.max(r.maxU,u);r.minV=Math.min(r.minV,v);r.maxV=Math.max(r.maxV,v)}r.area=(r.maxU-r.minU)*(r.maxV-r.minV);return r}
function detect(image){const small=image.clone();if(Math.max(small.bitmap.width,small.bitmap.height)>480)small.scaleToFit(480,480);const {width:w,height:h,data}=small.bitmap,n=w*h,mask=new Uint8Array(n),seen=new Uint8Array(n),queue=new Int32Array(n);for(let i=0;i<n;i++){const k=i*4,r=data[k],g=data[k+1],b=data[k+2],light=(r+g+b)/3;mask[i]=light>125&&Math.max(r,g,b)-Math.min(r,g,b)<100?1:0}let candidates=[];
  for(let begin=0;begin<n;begin++){if(!mask[begin]||seen[begin])continue;let head=0,tail=1;queue[0]=begin;seen[begin]=1;let points=[];while(head<tail){const i=queue[head++],x=i%w,y=Math.floor(i/w);let edge=false;for(const j of [x?i-1:-1,x<w-1?i+1:-1,y?i-w:-1,y<h-1?i+w:-1]){if(j<0||!mask[j])edge=true;else if(!seen[j]){seen[j]=1;queue[tail++]=j}}if(edge)points.push({x,y})}if(tail<n*.035||tail>n*.88)continue;const rect=rectangle(points);if(!rect)continue;const bw=rect.maxU-rect.minU,bh=rect.maxV-rect.minV,ratio=bw/bh,density=tail/rect.area,coverage=rect.area/n;if(ratio<1.45||ratio>1.80||density<.62||coverage>.88||bw<80||bh<50)continue;candidates.push({...rect,density,coverage,score:tail,width:w,height:h})}
  candidates.sort((a,b)=>b.score-a.score);if(candidates.length!==1)return null;const rect=candidates[0];let theta=rect.theta;while(theta>=Math.PI/2)theta-=Math.PI;while(theta< -Math.PI/2)theta+=Math.PI;const points=[];const c=Math.cos(rect.theta),s=Math.sin(rect.theta);for(const u of [rect.minU,rect.maxU])for(const v of [rect.minV,rect.maxV])points.push({x:u*c-v*s,y:u*s+v*c});return{...rectangleAt(points,theta),width:w,height:h,density:rect.density,coverage:rect.coverage}
}
async function processImage(buffer,documentType){const meta=dimensions(buffer);if(meta.width<50||meta.height<50||meta.width*meta.height>8000000)throw Error('IMAGE_DIMENSIONS');let image=await Jimp.read(buffer);if(Math.max(image.bitmap.width,image.bitmap.height)>1600)image.scaleToFit(1600,1600);const rect=documentType==='resident_id'?detect(image):null;let output=image,cropped=false,rotation=0;
  if(rect){const scaleX=image.bitmap.width/rect.width,scaleY=image.bitmap.height/rect.height;if(Math.abs(scaleX-scaleY)/scaleX<.015){const padding=Math.max(3,(rect.maxV-rect.minV)*.035);const u0=(rect.minU-padding)*scaleX,v0=(rect.minV-padding)*scaleY,width=Math.ceil((rect.maxU-rect.minU+padding*2)*scaleX),height=Math.ceil((rect.maxV-rect.minV+padding*2)*scaleY);if(width>=220&&height>=130){output=new Jimp(width,height,0xffffffff);const c=Math.cos(rect.theta),s=Math.sin(rect.theta),source=image.bitmap;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const sx=c*(u0+x)-s*(v0+y),sy=s*(u0+x)+c*(v0+y);const ix=Math.floor(sx),iy=Math.floor(sy);if(ix<0||iy<0||ix+1>=source.width||iy+1>=source.height)continue;const dx=sx-ix,dy=sy-iy,target=(y*width+x)*4;for(let k=0;k<3;k++){let a=source.data[(iy*source.width+ix)*4+k],b=source.data[(iy*source.width+ix+1)*4+k],d=source.data[((iy+1)*source.width+ix)*4+k],e=source.data[((iy+1)*source.width+ix+1)*4+k];output.bitmap.data[target+k]=Math.round(a*(1-dx)*(1-dy)+b*dx*(1-dy)+d*(1-dx)*dy+e*dx*dy)}}cropped=true;rotation=Number((-rect.theta*180/Math.PI).toFixed(2))}}}
  const data=await output.quality(88).getBufferAsync(Jimp.MIME_JPEG);return{data,cropDetected:cropped,rotation,width:output.bitmap.width,height:output.bitmap.height,needsOrientationConfirmation:true,message:cropped?'已自动旋转裁边，请确认文字朝向':'边框不明确，已保留完整照片，请确认朝向'}
}
module.exports={processImage,dimensions,detect}
