var workspace = require('../../../utils/workspace')

Page({
  data: { inviteId: '', loading: true, accepting: false, invite: {}, tournament: {}, prebuiltTeam: {}, candidateTeams: [], selectedTeamId: '', selectedTeamName: '', hasCandidate: false, reviewRequired: false, reviewApproved: false, showPrebuiltInfo: false, showPrebuiltOption: false, showExistingOption: false, showReviewAction: false, disclaimerAgreed: false, disclaimerCheckboxClass: '', acceptDisabled: true, existingActionLabel: '使用现有球队接收', prebuiltActionLabel: '接收预建队伍', errorText: '', isDevtools: false },
  onLoad: function (options) { var query = options || {}; var inviteId = String(query.inviteId || query.scene || ''); var qa = workspace.isVisualQaEnabled(query); this.setData({ inviteId: decodeURIComponent(inviteId), isDevtools: qa }); if (qa) { this.setData({ loading: false, invite: { divisionName: 'U12组', managerName: '刘教练', managerPhoneMasked: '186****3345' }, tournament: { name: '2026 河南青少年足球冠军联赛' }, prebuiltTeam: { name: '平顶山飞豹U12队', requiresReview: false }, candidateTeams: [{ id: 'qa-existing-u12', name: '平顶山飞豹青训U12队', playerCount: 23 }], hasCandidate: true, showExistingOption: true, showPrebuiltInfo: false, showPrebuiltOption: false, showReviewAction: false }); return } this.load() },
  // 队长已有自己的球队时不再展示主办方预建信息与「接收预建队伍」，只允许用现有球队接收。
  // 没有既有球队时保留预建接收：产品规则 11 要求「已有长期球队时优先用自己的球队，没有球队时才接收预建球队」。
  // 归属冲突经人工核验通过后服务端只接受 choice='prebuilt'（getMiniWorkspace:2039），该入口必须保留。
  load: function () { var self = this; wx.cloud.callFunction({ name: 'getMiniWorkspace', data: { action: 'prebuiltTeamInvite', inviteId: this.data.inviteId } }).then(function (res) { var result = res.result || {}; if (!result.success) throw new Error(result.message || '邀请加载失败'); var teams = result.candidateTeams || []; var reviewRequired = Boolean((result.prebuiltTeam || {}).requiresReview); var reviewApproved = String((result.invite || {}).status || '') === 'review_approved'; var hasCandidate = teams.length > 0; var showPrebuiltOption = !hasCandidate || reviewApproved; self.setData({ loading: false, invite: result.invite || {}, tournament: result.tournament || {}, prebuiltTeam: result.prebuiltTeam || {}, candidateTeams: teams, hasCandidate: hasCandidate, reviewRequired: reviewRequired, reviewApproved: reviewApproved, showPrebuiltInfo: !hasCandidate, showPrebuiltOption: showPrebuiltOption, showExistingOption: hasCandidate && !reviewApproved, showReviewAction: reviewRequired && !reviewApproved, existingActionLabel: '使用现有球队接收', prebuiltActionLabel: reviewApproved ? '人工核验已通过，确认接收预建球队' : '接收预建队伍' }, function () { self.refreshActionState() }) }).catch(function (error) { self.setData({ loading: false, errorText: error.message || '邀请加载失败' }) }) },
  chooseExisting: function (event) { this.setData({ selectedTeamId: event.currentTarget.dataset.id, selectedTeamName: event.currentTarget.dataset.name, candidateTeams: this.data.candidateTeams.map(function (item) { var row = Object.assign({}, item); row.className = row.id === event.currentTarget.dataset.id ? 'candidate candidate-selected' : 'candidate'; return row }) }) },
  refreshActionState: function () { this.setData({ disclaimerCheckboxClass: this.data.disclaimerAgreed ? 'checked' : '', acceptDisabled: this.data.accepting || (this.data.reviewRequired && !this.data.reviewApproved) || !this.data.disclaimerAgreed }) },
  toggleDisclaimer: function () { this.setData({ disclaimerAgreed: !this.data.disclaimerAgreed }, this.refreshActionState) },
  acceptExisting: function () { if (this.data.reviewRequired) { this.openClaimConflict(); return } if (!this.data.selectedTeamId) { wx.showToast({ title: '请选择一支现有球队', icon: 'none' }); return } this.accept('existing', this.data.selectedTeamId) },
  openClaimConflict: function () { wx.redirectTo({ url: '/pages/team/claim-conflict/claim-conflict?inviteId=' + encodeURIComponent(this.data.inviteId) + '&teamName=' + encodeURIComponent(this.data.prebuiltTeam.name || '') + '&tournamentName=' + encodeURIComponent(this.data.tournament.name || '') + '&divisionName=' + encodeURIComponent(this.data.invite.divisionName || '') }) },
  acceptPrebuilt: function () { this.accept('prebuilt', '') },
  accept: function (choice, existingTeamId) { var self = this; if (this.data.accepting) return; if (!this.data.disclaimerAgreed) { wx.showToast({ title: '请先同意参赛免责声明', icon: 'none' }); return } this.setData({ accepting: true }, this.refreshActionState); wx.cloud.callFunction({ name: 'getMiniWorkspace', data: { action: 'acceptPrebuiltTeamInvite', inviteId: this.data.inviteId, choice: choice, existingTeamId: existingTeamId, disclaimerAgreed: true } }).then(function (res) { var result = res.result || {}; if (!result.success) throw new Error(result.message || '接收失败'); if (result.reviewRequired) { wx.redirectTo({ url: '/pages/team/claim-conflict/claim-conflict?inviteId=' + encodeURIComponent(self.data.inviteId) + '&teamName=' + encodeURIComponent(self.data.prebuiltTeam.name || '') + '&tournamentName=' + encodeURIComponent(self.data.tournament.name || '') + '&divisionName=' + encodeURIComponent(self.data.invite.divisionName || '') }); return } wx.showToast({ title: '球队已认领', icon: 'success' }); var target = Number(result.pendingPlayerDraftCount || 0) > 0 ? '/pages/team/imported-player-review/imported-player-review?teamId=' : '/pages/team/team?teamId='; wx.redirectTo({ url: target + encodeURIComponent(result.teamId) }) }).catch(function (error) { wx.showToast({ title: error.message || '接收失败', icon: 'none' }) }).finally(function () { self.setData({ accepting: false }, self.refreshActionState) }) },
  back: function () { wx.navigateBack() }
})
