var workspace = require('../../../utils/workspace')
Page({
  data: { teamId: '', tournamentId: '', divisionId: 'default', loading: true, requesting: false, tournament: {}, division: {}, package: {}, canRequest: false, isProfessional: false, isRequested: false, isEnabled: false, primaryText: '了解并开通', subtitle: '', isDevtools: false, features: [] },
  onLoad: function (options) { var query = options || {}; var qa = workspace.isVisualQaEnabled(query); this.setData({ teamId: String(query.teamId || ''), tournamentId: String(query.tournamentId || ''), divisionId: String(query.divisionId || 'default'), isDevtools: qa }); if (qa) { this.setData({ loading: false, tournament: { name: '2026 河南青少年足球冠军联赛' }, division: { name: 'U12组' }, canRequest: true, features: [{ icon: '/images/runtime/icons/brand-v2-11.png', title: '裁判录入事件时可直接选择本队球员', desc: '无需手动输入，快速准确记录比赛事件' }, { icon: '/images/runtime/icons/brand-v2-16.png', title: '进球、助攻、出场等数据长期归入球员档案', desc: '完整沉淀球员在本队的成长轨迹与比赛表现' }, { icon: '/images/runtime/icons/brand-v2-13.png', title: '赛事结束后可查看并导出本队数据', desc: '按需筛选、统计与导出，方便复盘与存档' }, { icon: '/images/runtime/icons/brand-v2-06.png', title: '后续可与球队自己的教务系统对接', desc: '打通数据链路，助力球队科学训练与管理' }] }); return } this.load() },
  load: function () { var self = this, context = workspace.readContext() || {}; wx.cloud.callFunction({ name: 'getMiniWorkspace', data: { action: 'teamDataPackage', workspaceId: (context.currentWorkspace || {}).id, teamId: this.data.teamId, tournamentId: this.data.tournamentId, divisionId: this.data.divisionId } }).then(function (res) { var result = res.result || {}, status = ((result.package || {}).status || ''); if (!result.success) throw new Error(result.message || '数据包加载失败'); self.setData({ loading: false, tournament: result.tournament || {}, division: result.division || {}, package: result.package || {}, canRequest: result.canRequest, isProfessional: (result.division || {}).professional, isRequested: status === 'requested' || status === 'enabled', isEnabled: status === 'enabled', primaryText: status === 'requested' ? '开通申请已提交' : (status === 'enabled' ? '查看赛事数据' : '了解并开通'), subtitle: (result.division || {}).professional ? '专业组别已包含球队数据能力，不显示购买入口。' : '', features: [{ icon: '/images/runtime/icons/brand-v2-11.png', title: '裁判录入事件时可直接选择本队球员', desc: '无需手动输入，快速准确记录比赛事件' }, { icon: '/images/runtime/icons/brand-v2-16.png', title: '进球、助攻、出场等数据长期归入球员档案', desc: '完整沉淀球员在本队的成长轨迹与比赛表现' }, { icon: '/images/runtime/icons/brand-v2-13.png', title: '赛事结束后可查看并导出本队数据', desc: '按需筛选、统计与导出，方便复盘与存档' }, { icon: '/images/runtime/icons/brand-v2-06.png', title: '后续可与球队自己的教务系统对接', desc: '打通数据链路，助力球队科学训练与管理' }] }) }).catch(function (error) { self.setData({ loading: false }); wx.showToast({ title: error.message || '数据包加载失败', icon: 'none' }) }) },
  request: function () { var self = this, context = workspace.readContext() || {}; if (!this.data.canRequest || this.data.isRequested || this.data.requesting) return; this.setData({ requesting: true }); wx.cloud.callFunction({ name: 'getMiniWorkspace', data: { action: 'requestTeamDataPackage', workspaceId: (context.currentWorkspace || {}).id, teamId: this.data.teamId, tournamentId: this.data.tournamentId, divisionId: this.data.divisionId } }).then(function (res) { var result = res.result || {}; if (!result.success) throw new Error(result.message || '申请失败'); wx.showToast({ title: '开通申请已提交', icon: 'success' }); self.load() }).catch(function (error) { wx.showToast({ title: error.message || '申请失败', icon: 'none' }) }).finally(function () { self.setData({ requesting: false }) }) },
  openData: function () { wx.navigateTo({ url: '/pages/team/data-package-events/data-package-events?teamId=' + encodeURIComponent(this.data.teamId) + '&tournamentId=' + encodeURIComponent(this.data.tournamentId) + '&divisionId=' + encodeURIComponent(this.data.divisionId) }) },
  back: function () { wx.navigateBack() }
})
