var workspace = require('../../../utils/workspace')
function isDevtools() { try { return wx.getSystemInfoSync().platform === 'devtools' } catch (error) { return false } }
Page({
  data: { teamId: '', loading: true, saving: false, canManage: false, editing: false, profile: {}, form: {}, completenessText: '0%', localVisualQa: false },
  onLoad: function (options) { if (isDevtools() && options && options.visualQa === '1') { var profile = { name: '赛小蜂 U12 竞技队', shortName: '赛小蜂U12', ageGroup: 'U12（2014 年龄段）', foundedYear: '2018', city: '河南省郑州市', managerName: '许老师', managerPhoneMasked: '173****1663', orgName: '赛小蜂足球俱乐部', claimText: '已认领', completeness: 92, logo: '/images/runtime/icons/brand-v1-tab-team.png' }; this.setData({ teamId: 'visual-qa-u12', loading: false, canManage: true, localVisualQa: true, profile: profile, form: profile, completenessText: '92%' }); return }; this.setData({ teamId: String((options || {}).teamId || (options || {}).id || '') }); this.load() },
  load: function () { var self = this, context = workspace.readContext() || {}; wx.cloud.callFunction({ name: 'getMiniWorkspace', data: { action: 'teamProfile', workspaceId: (context.currentWorkspace || {}).id, teamId: this.data.teamId } }).then(function (res) { var result = res.result || {}; if (!result.success) throw new Error(result.message || '资料加载失败'); var profile = result.profile || {}; self.setData({ loading: false, profile: profile, form: profile, canManage: result.canManage, completenessText: String(profile.completeness || 0) + '%' }) }).catch(function (error) { self.setData({ loading: false }); wx.showToast({ title: error.message || '资料加载失败', icon: 'none' }) }) },
  edit: function () { if (this.data.canManage) this.setData({ editing: true }) },
  cancel: function () { this.setData({ editing: false, form: this.data.profile }) },
  input: function (event) { var key = event.currentTarget.dataset.key; this.setData({ ['form.' + key]: event.detail.value }) },
  save: function () { var self = this, context = workspace.readContext() || {}; if (this.data.saving) return; this.setData({ saving: true }); wx.cloud.callFunction({ name: 'getMiniWorkspace', data: Object.assign({ action: 'saveTeamProfile', workspaceId: (context.currentWorkspace || {}).id, teamId: this.data.teamId }, this.data.form) }).then(function (res) { if (!(res.result || {}).success) throw new Error((res.result || {}).message || '保存失败'); wx.showToast({ title: '球队资料已保存', icon: 'success' }); self.setData({ editing: false }); self.load() }).catch(function (error) { wx.showToast({ title: error.message || '保存失败', icon: 'none' }) }).finally(function () { self.setData({ saving: false }) }) },
  back: function () { wx.navigateBack() }
})
